let tiVi = new Tv(2,5)
let remote = new Remote(2)
// tiVi.getSound()
// tiVi.getChannel()
// remote.controlTv(tiVi)
// tiVi.getSound()
// tiVi.getChannel()
remote.controlTv(tiVi)
tiVi.getSound()
tiVi.getChannel()
remote.channelControl(tiVi,3)
remote.soundControlUp(tiVi,2)
tiVi.getSound()
tiVi.getChannel()
remote.soundControlDown(tiVi,4)
tiVi.getSound()
// remote.controlTv(tiVi)